name: GA4 to Snowflake Daily Pipeline

on:
  schedule:
    - cron: '*/4 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Test Scheduling
        run: echo "Scheduled run working at $(date)"
